// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dev-hyunsang/clone-todo-mate/ent/todo"
	"github.com/google/uuid"
)

// ToDo is the model entity for the ToDo schema.
type ToDo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TodoUUID holds the value of the "todo_uuid" field.
	TodoUUID uuid.UUID `json:"todo_uuid,omitempty"`
	// UserUUID holds the value of the "user_uuid" field.
	UserUUID uuid.UUID `json:"user_uuid,omitempty"`
	// TodoContext holds the value of the "todo_context" field.
	TodoContext string `json:"todo_context,omitempty"`
	// Completion holds the value of the "completion" field.
	Completion bool `json:"completion,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// EditedAt holds the value of the "edited_at" field.
	EditedAt time.Time `json:"edited_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ToDo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case todo.FieldCompletion:
			values[i] = new(sql.NullBool)
		case todo.FieldID:
			values[i] = new(sql.NullInt64)
		case todo.FieldTodoContext:
			values[i] = new(sql.NullString)
		case todo.FieldCompletedAt, todo.FieldCreatedAt, todo.FieldEditedAt:
			values[i] = new(sql.NullTime)
		case todo.FieldTodoUUID, todo.FieldUserUUID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ToDo", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ToDo fields.
func (td *ToDo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case todo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			td.ID = int(value.Int64)
		case todo.FieldTodoUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field todo_uuid", values[i])
			} else if value != nil {
				td.TodoUUID = *value
			}
		case todo.FieldUserUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_uuid", values[i])
			} else if value != nil {
				td.UserUUID = *value
			}
		case todo.FieldTodoContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field todo_context", values[i])
			} else if value.Valid {
				td.TodoContext = value.String
			}
		case todo.FieldCompletion:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field completion", values[i])
			} else if value.Valid {
				td.Completion = value.Bool
			}
		case todo.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				td.CompletedAt = value.Time
			}
		case todo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				td.CreatedAt = value.Time
			}
		case todo.FieldEditedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field edited_at", values[i])
			} else if value.Valid {
				td.EditedAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this ToDo.
// Note that you need to call ToDo.Unwrap() before calling this method if this ToDo
// was returned from a transaction, and the transaction was committed or rolled back.
func (td *ToDo) Update() *ToDoUpdateOne {
	return (&ToDoClient{config: td.config}).UpdateOne(td)
}

// Unwrap unwraps the ToDo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (td *ToDo) Unwrap() *ToDo {
	_tx, ok := td.config.driver.(*txDriver)
	if !ok {
		panic("ent: ToDo is not a transactional entity")
	}
	td.config.driver = _tx.drv
	return td
}

// String implements the fmt.Stringer.
func (td *ToDo) String() string {
	var builder strings.Builder
	builder.WriteString("ToDo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", td.ID))
	builder.WriteString("todo_uuid=")
	builder.WriteString(fmt.Sprintf("%v", td.TodoUUID))
	builder.WriteString(", ")
	builder.WriteString("user_uuid=")
	builder.WriteString(fmt.Sprintf("%v", td.UserUUID))
	builder.WriteString(", ")
	builder.WriteString("todo_context=")
	builder.WriteString(td.TodoContext)
	builder.WriteString(", ")
	builder.WriteString("completion=")
	builder.WriteString(fmt.Sprintf("%v", td.Completion))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(td.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(td.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("edited_at=")
	builder.WriteString(td.EditedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ToDos is a parsable slice of ToDo.
type ToDos []*ToDo

func (td ToDos) config(cfg config) {
	for _i := range td {
		td[_i].config = cfg
	}
}
